deployments:
  environmentMapping:
    development:
      - "dev*"
      - "entw*"
      - "baz*"
      - "foo*"
    staging:
      - "pre*"
    testing:
      - "test*"
    production:
      - "prod*"
